services:
  - type: web
    name: ra-crawler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash scripts/start.sh
    envVars:
      - key: DATABASE_URL
        value: sqlite:////data/racing.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
