services:
  # --- Public API ---
  - type: web
    name: racing-api
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: sqlite:////data/racing.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

  # --- Nightly crawler job (writes to the same /data DB) ---
  - type: cron
    name: racing-crawler
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    schedule: "0 16 * * *"   # runs daily at 16:00 UTC (~ 2am AEST / 3am AEDT). Change as you like.
    startCommand: python -m api.crawl_calendar --days 30 --include-past 2 --force
    envVars:
      - key: DATABASE_URL
        value: sqlite:////data/racing.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
