services:
  - type: web
    name: ra-crawler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash scripts/start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RA_DB_VERBOSE
        value: "1"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
